<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5572c1e62605f',
	'title' => 'Two Column Content',
	'fields' => array (
		array (
			'key' => 'field_5572c1faaf513',
			'label' => 'Columns',
			'name' => 'columns',
			'type' => 'repeater',
			'instructions' => 'To use the following content, simply use the shortcode [pbz_columns]',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_5572c20eaf514',
					'label' => 'Image Position',
					'name' => 'image_position',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Left' => 'Left',
						'Right' => 'Right',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'Left',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_5572c23daf515',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_5572c256af516',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'logo-standard',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_55735baec9744',
					'label' => 'Website',
					'name' => 'website',
					'type' => 'url',
					'instructions' => 'Good if you want to link the image out to an external site.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_565005c30644b',
	'title' => 'Blitz Events',
	'fields' => array (
		array (
			'key' => 'field_565005dc9f683',
			'label' => 'Blurb for email',
			'name' => 'blurb_for_email',
			'type' => 'wysiwyg',
			'instructions' => 'Don\'t add images to this - keep to a single paragraph, maybe two. No need to add any links or anything like that.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_57a5c486af7e7',
			'label' => 'Booked Out',
			'name' => 'booked_out',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'This event is booked out',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'event-categories:upcoming-blitzes',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5650013419a12',
	'title' => 'Blitz Notifications',
	'fields' => array (
		array (
			'key' => 'field_5650014070b17',
			'label' => 'Blitz to promote',
			'name' => 'blitz_to_promote',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'event',
			),
			'taxonomy' => array (
				0 => 'event-categories:upcoming-blitzes',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_57c2aeeae8684',
			'label' => 'Preview Text',
			'name' => 'preview_text',
			'type' => 'text',
			'instructions' => 'This will not be shown in the email body, but is used by a lot of email clients to provide a preview of the email\'s content. Limited to 75 characters - try to cover the meat of the email\'s content here for better open rates.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 75,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5650017a70b18',
			'label' => 'Send Type',
			'name' => 'send_type',
			'type' => 'radio',
			'instructions' => 'Make sure you do a test send first!!',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Test email' => 'Test email',
				'Send to Signups' => 'Send to Signups',
				'Send to Biz' => 'Send to Biz',
				'Send to AutoBlitz list' => 'Send to AutoBlitz list',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Test email',
			'layout' => 'vertical',
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_570565f302e22',
			'label' => 'Which form are we getting the emails from?',
			'name' => 'which_group',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5650017a70b18',
						'operator' => '==',
						'value' => 'Send to Signups',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				15 => 'Ania',
				14 => 'Blitz Request - Designer signup',
				4 => 'Contact Us',
				10 => 'Designers Wanted',
				9 => 'Get Blitzed!',
				13 => 'Permablitz Booking - #170 - Seddon',
				12 => 'Register',
				11 => 'Subscribe',
				16 => 'Volunteer Dropouts',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_565001f170b19',
			'label' => 'Recipients',
			'name' => 'recipients',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5650017a70b18',
						'operator' => '==',
						'value' => 'Test email',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Email Address',
			'sub_fields' => array (
				array (
					'key' => 'field_5650020270b1a',
					'label' => 'Email',
					'name' => 'email',
					'type' => 'email',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
			'collapsed' => '',
		),
		array (
			'key' => 'field_5706334758086',
			'label' => 'Do you need a custom message?',
			'name' => 'custom_message',
			'type' => 'true_false',
			'instructions' => 'Custom messages are really only needed for when sending notifications to volunteers.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, I want to replace the default copy with a custom message',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_57064b3448086',
			'label' => 'Custom Subject Line',
			'name' => 'custom_subject_line',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5706334758086',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Permablitz #178 - just a few more days!',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5706339c58087',
			'label' => 'Message',
			'name' => 'message',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5706334758086',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'It\'s just a few days to go now - it\'s going to be great!

If you can no longer attend, please let the host know as soon as possible. This will allow us to ensure those on the back-up list have the opportunity to join in the fun!

We look forward to seeing you there - if you\'re on Instagram and are taking pics on the day, please use the hashtag #permablitz177 so we can include your pics on the report of day\'s events.

And remember - have fun!

From the team @ Permablitz decentral',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_565589fee28d4',
			'label' => 'Notes',
			'name' => 'notes',
			'type' => 'textarea',
			'instructions' => 'No need to fill this in - this will provide feedback on the send success.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 12,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'intant-blitz-notification',
			),
		),
		array (
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'newsletter_category:instant-blitz-notification',
			),
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'newsletter',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Please note that this will not allow you to send info on the same Blitz twice.',
));

acf_add_local_field_group(array (
	'key' => 'group_55f50a9021ca6',
	'title' => 'Schedule Emails',
	'fields' => array (
		array (
			'key' => 'field_55f50aeb507b0',
			'label' => 'Recipient Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55f50aa0507ad',
			'label' => 'Recipient First Name',
			'name' => 'recipient_first_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55f50ac8507ae',
			'label' => 'Recipient Last Name',
			'name' => 'recipient_last_name',
			'type' => 'text',
			'instructions' => 'Optional',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55f50adf507af',
			'label' => 'Recipient\'s Email',
			'name' => 'recipients_email',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_55f50b1679238',
			'label' => 'Email Setup',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55f50b2579239',
			'label' => 'Email Type',
			'name' => 'email_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Host - Follow-up survey' => 'Host - Follow-up survey',
				'Host - Two weeks before the blitz' => 'Host - Two weeks before the blitz',
				'Designer - Follow up survey' => 'Designer - Follow up survey',
				'Documenter - check in before blitz' => 'Documenter - check in before blitz',
				'Facilitator - check in before blitz' => 'Facilitator - check in before blitz',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55f50bb67923a',
			'label' => 'Email Send Date',
			'name' => 'email_send_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array (
			'key' => 'field_55f50c987923c',
			'label' => 'Email Send Hour',
			'name' => 'email_send_hour',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'00:00:00 12:00am' => '00:00:00 12:00am',
				'03:00:00 3:00am' => '03:00:00 3:00am',
				'06:00:00 6:00am' => '06:00:00 6:00am',
				'09:00:00 9:00am' => '09:00:00 9:00am',
				'12:00:00 12:00pm' => '12:00:00 12:00pm',
				'15:00:00 3:00pm' => '15:00:00 3:00pm',
				'18:00:00 6:00pm' => '18:00:00 6:00pm',
				'21:00:00 9:00pm' => '21:00:00 9:00pm',
			),
			'default_value' => array (
				'09:00:00' => '09:00:00',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-schedule-emails',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5686d87aec09b',
	'title' => 'Google Maps for Blitz Requests',
	'fields' => array (
		array (
			'key' => 'field_56875df1858a3',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'wysiwyg',
			'instructions' => 'This will be shown at the top of the list of Blitz Requests',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_5686d87b1138b',
			'label' => 'Do you want to add Map Locations?',
			'name' => 'do_you_want_to_add_map_locations',
			'type' => 'true_false',
			'instructions' => 'This will show a map of all locations requiring blitzes. Will eventually automate this.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, I want to add a map to this page',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5686d87b1156f',
			'label' => 'Map Locations',
			'name' => 'map_locations',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5686d87b1138b',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Location',
			'sub_fields' => array (
				array (
					'key' => 'field_5686d87b20780',
					'label' => 'Location',
					'name' => 'location',
					'type' => 'google_map',
					'instructions' => 'Don\'t enter specific street numbers for private residences!',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'center_lat' => '',
					'center_lng' => '',
					'zoom' => '',
					'height' => 200,
				),
				array (
					'key' => 'field_5686d87b20b8a',
					'label' => 'Page Link',
					'name' => 'page_link',
					'type' => 'post_object',
					'instructions' => 'Optional link to previous blitzes',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'blitz-request',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
		array (
			'key' => 'field_56a1b8cf7f830',
			'label' => 'Default login message',
			'name' => 'default_login_message',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-map-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5789df5bb728d',
	'title' => 'Groups',
	'fields' => array (
		array (
			'key' => 'field_5789df6288741',
			'label' => 'Area',
			'name' => 'area',
			'type' => 'repeater',
			'instructions' => 'To add this to your page, please use the shortcode [pbz_groups]',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5789fd40aab7a',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Group',
			'sub_fields' => array (
				array (
					'key' => 'field_5789fd40aab7a',
					'label' => 'Area Name',
					'name' => 'area_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5789f98cb3010',
					'label' => 'Groups',
					'name' => 'groups',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5789f9abb3011',
					'min' => '',
					'max' => '',
					'layout' => 'row',
					'button_label' => 'Add Group',
					'sub_fields' => array (
						array (
							'key' => 'field_5789f9abb3011',
							'label' => 'Group Name',
							'name' => 'group_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5789f9d2b3012',
							'label' => 'Website',
							'name' => 'website',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5789f9dbb3013',
							'label' => 'Facebook Page',
							'name' => 'facebook_page',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5789f9ecb3014',
							'label' => 'Extra Info',
							'name' => 'extra_info',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
						),
						array (
							'key' => 'field_5789fa0cb3015',
							'label' => 'Map Location',
							'name' => 'map_location',
							'type' => 'google_map',
							'instructions' => 'If you don\'t have an address, the town/city name will do!',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'center_lat' => '',
							'center_lng' => '',
							'zoom' => '',
							'height' => '',
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-maps.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56b6d9f4caaee',
	'title' => 'Blitz Requests',
	'fields' => array (
		array (
			'key' => 'field_56b6d9fab1983',
			'label' => 'Map Location',
			'name' => 'map_location',
			'type' => 'google_map',
			'instructions' => 'Just enter the suburb, no need for street information! (Privacy!!)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
		array (
			'key' => 'field_56b6da1ab1984',
			'label' => 'Interested Designers',
			'name' => 'interested_designers',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => 4,
			'layout' => 'row',
			'button_label' => 'Add Designer',
			'sub_fields' => array (
				array (
					'key' => 'field_56b6da2cb1985',
					'label' => 'Designer',
					'name' => 'designer',
					'type' => 'user',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'role' => array (
						0 => 'designer',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_56b852e468ece',
					'label' => 'Approved',
					'name' => 'approved',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'This person is approved to be a Designer for this Blitz!',
					'default_value' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'blitz-request',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56a0a257698a9',
	'title' => 'Guild Notifications',
	'fields' => array (
		array (
			'key' => 'field_56a0a6723c2e0',
			'label' => 'Subject',
			'name' => 'subject',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Design needed in ***',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56a0a6973c2e1',
			'label' => 'Intro Text',
			'name' => 'intro_text',
			'type' => 'textarea',
			'instructions' => 'If used, this will go beneath the hero image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56b853338537d',
			'label' => 'Blitz or Event?',
			'name' => 'blitz_or_event',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Blitz' => 'Blitz',
				'Event (eg Guild Session)' => 'Event (eg Guild Session)',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Blitz',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_56a0a25782dd0',
			'label' => 'Blitz to promote',
			'name' => 'guild_blitz_to_promote',
			'type' => 'post_object',
			'instructions' => 'This will pull the hero image from the post for the email',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b853338537d',
						'operator' => '==',
						'value' => 'Blitz',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'blitz-request',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_56b853608537e',
			'label' => 'Event to promote',
			'name' => 'guild_event_to_promote',
			'type' => 'post_object',
			'instructions' => 'This will pull the hero image from the event for the email',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b853338537d',
						'operator' => '==',
						'value' => 'Event (eg Guild Session)',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'event',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_56a0a257831bb',
			'label' => 'Send Type',
			'name' => 'guild_send_type',
			'type' => 'radio',
			'instructions' => 'Make sure you do a test send first!!',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Test email' => 'Test email',
				'Send to Signups' => 'Send to Signups',
				'Send to Biz' => 'Send to Biz',
				'Send to the Guild' => 'Send to the Guild',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Test email',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_56a0a257835a9',
			'label' => 'Recipients',
			'name' => 'guild_recipients',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56a0a257831bb',
						'operator' => '==',
						'value' => 'Test email',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Email Address',
			'sub_fields' => array (
				array (
					'key' => 'field_56a0a257a8dc3',
					'label' => 'Email',
					'name' => 'email',
					'type' => 'email',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array (
			'key' => 'field_56d72a21cffe5',
			'label' => 'Which form are we getting the emails from?',
			'name' => 'which_group',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56a0a257831bb',
						'operator' => '==',
						'value' => 'Send to Signups',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				14 => 'Blitz Request - Designer signup',
				4 => 'Contact Us',
				10 => 'Designers Wanted',
				9 => 'Get Blitzed!',
				13 => 'Permablitz Booking - #170 -...',
				12 => 'Register',
				11 => 'Subscribe',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56a0a2578398e',
			'label' => 'Notes',
			'name' => 'guild_notes',
			'type' => 'textarea',
			'instructions' => 'No need to fill this in - this will provide feedback on the send success.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 12,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-guild-notifications',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Please note that this will not allow you to send info on the same Blitz twice.',
));

acf_add_local_field_group(array (
	'key' => 'group_56a8837882268',
	'title' => 'Facebook Posts',
	'fields' => array (
		array (
			'key' => 'field_56a88385327ea',
			'label' => 'Permablitz FB URL',
			'name' => 'permablitz_fb_url',
			'type' => 'url',
			'instructions' => 'This is the Permablitz Facebook Page link',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_56a883a0327eb',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'fb-thumb',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'fb-post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56a9dbb51e80b',
	'title' => 'Post Options',
	'fields' => array (
		array (
			'key' => 'field_56a9dbc12718a',
			'label' => 'Do you want Facebook posts to be shown?',
			'name' => 'facebook_onscreen',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, show the Facebook posts',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56a9dbf82718b',
			'label' => 'Facebook Posts',
			'name' => 'facebook_posts',
			'type' => 'repeater',
			'instructions' => 'Remember - it\'s best to show six!
To add, just include [facebook_posts]',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56a9dbc12718a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Post',
			'sub_fields' => array (
				array (
					'key' => 'field_56a9dc1d2718c',
					'label' => 'Post',
					'name' => 'post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'fb-post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 1,
				),
			),
		),
		array (
			'key' => 'field_585e224d7aa9d',
			'label' => 'Do you want to show a map?',
			'name' => 'show_prev_blitz_map',
			'type' => 'true_false',
			'instructions' => 'This is typically to show previous blitz locations. Show on the page with the shortcode [prev_blitzes_map]',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, I want to show a map',
			'default_value' => 0,
		),
		array (
			'key' => 'field_585e22607aa9e',
			'label' => 'Map Locations',
			'name' => 'map_locations',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_585e224d7aa9d',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_585e22967aaa0',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Location',
			'sub_fields' => array (
				array (
					'key' => 'field_585e22967aaa0',
					'label' => 'Post to link to',
					'name' => 'post_to_link_to',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'post',
					),
					'taxonomy' => array (
						0 => 'category:past-blitzes',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_585e22717aa9f',
					'label' => 'Location',
					'name' => 'location',
					'type' => 'google_map',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'center_lat' => '',
					'center_lng' => '',
					'zoom' => '',
					'height' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56a0a257698a9',
	'title' => 'Guild Notifications',
	'fields' => array (
		array (
			'key' => 'field_56a0a6723c2e0',
			'label' => 'Subject',
			'name' => 'subject',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Design needed in ***',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56a0a6973c2e1',
			'label' => 'Intro Text',
			'name' => 'intro_text',
			'type' => 'textarea',
			'instructions' => 'If used, this will go beneath the hero image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56b853338537d',
			'label' => 'Blitz or Event?',
			'name' => 'blitz_or_event',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Blitz' => 'Blitz',
				'Event (eg Guild Session)' => 'Event (eg Guild Session)',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Blitz',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_56a0a25782dd0',
			'label' => 'Blitz to promote',
			'name' => 'guild_blitz_to_promote',
			'type' => 'post_object',
			'instructions' => 'This will pull the hero image from the post for the email',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b853338537d',
						'operator' => '==',
						'value' => 'Blitz',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'blitz-request',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_56b853608537e',
			'label' => 'Event to promote',
			'name' => 'guild_event_to_promote',
			'type' => 'post_object',
			'instructions' => 'This will pull the hero image from the event for the email',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56b853338537d',
						'operator' => '==',
						'value' => 'Event (eg Guild Session)',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'event',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_56a0a257831bb',
			'label' => 'Send Type',
			'name' => 'guild_send_type',
			'type' => 'radio',
			'instructions' => 'Make sure you do a test send first!!',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Test email' => 'Test email',
				'Send to Biz' => 'Send to Biz',
				'Send to the Guild' => 'Send to the Guild',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Test email',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_56a0a257835a9',
			'label' => 'Recipients',
			'name' => 'guild_recipients',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56a0a257831bb',
						'operator' => '==',
						'value' => 'Test email',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Email Address',
			'sub_fields' => array (
				array (
					'key' => 'field_56a0a257a8dc3',
					'label' => 'Email',
					'name' => 'email',
					'type' => 'email',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array (
			'key' => 'field_56a0a2578398e',
			'label' => 'Notes',
			'name' => 'guild_notes',
			'type' => 'textarea',
			'instructions' => 'No need to fill this in - this will provide feedback on the send success.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 12,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-guild-notifications',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Please note that this will not allow you to send info on the same Blitz twice.',
));

endif;
?>